### ISSUE TITLE
Consider also tagging the major version

### ISSUE THREAD

**Issue by qrkourier** [jason-dour/action-setup-gomplate#4]
Thank you for providing patch release tags. Additionally, it is a GitHub Actions convention to provide a major version tag like `v1` that is routinely updated to reflect the latest release of the same, reverse-compatible major version. Please consider also tagging the major version so that consumers who pin the major version will automatically receive minor and patch releases.

**Comment by jason-dour** [comment]
Thanks for the feedback, @qrkourier 

I'll look at integrating this as part of this and other actions.  Appreciated.  :)

**Comment by qrkourier** [comment]
Sure thing and good luck! I found this Action to keep my project's major version tag updated to point at the latest release of the same major version.

https://github.com/marketplace/actions/actions-tagger

**Comment by jason-dour** [comment]
About to push new release.  Will tag with major version.
