### ISSUE TITLE
Missing support for Node 20

### ISSUE THREAD

**Issue by Bl00D4NGEL** [jason-dour/action-setup-gomplate#5]
This GH action currently produces the following warning when running:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: jason-dour/action-setup-gomplate@v1.0.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Please consider adding support (or rather a new major version I suppose) to set the default runtime to `node20` instead of `node16`.

I would do the change/PR myself but I'm afraid I never really implemented any GH action, although my guess be that one just has to change https://github.com/jason-dour/action-setup-gomplate/blob/main/action.yml#L16 to `node20`

**Comment by jason-dour** [comment]
I'll get to this soon.  Thank you for opening the issue.  :)

**Comment by jason-dour** [comment]
Added and confirmed with recent updates.
